rm_manual:
  robot_type: "engineer"
  chassis:
    topic: "/controllers/chassis_controller/command"
    accel_x: 3.0
    accel_y: 3.0
    accel_z: 20.0
    safety_power: 50.0
    capacitor_threshold: 0.1
    charge_power: 0
    extra_power: 5000
    burst_power: 500
  vel:
    topic: "/cmd_vel"
    max_linear_x: 2.0
    max_linear_y: 2.0
    max_angular_z: 20.0
  gimbal:
    topic: "/controllers/gimbal_controller/command"
    max_yaw_vel: 12.56
    max_pitch_vel: 8.37
    target_cost_function:
      k_pos: 1.0
      k_vel: 1.0
      k_hp: 1.0
      k_freq: 1.0
      timeout: 0.05
  mast:
    topic: "/controllers/mast_controller/command"
    on_pos: 0.
    off_pos: 0.
  card:
    topic: "/controllers/card_controller/command"
    on_pos: 0.28
    off_pos: 0.0
  stone_platform:
    topic: "/controllers/stone_platform_controller/command"
    on_pos: 0.19
    off_pos: 0.0

  controllers_list:
    state_controllers:
      - controllers/robot_state_controller
      - controllers/joint_state_controller
    main_controllers:
      - controllers/chassis_controller
      - controllers/gimbal_controller
      - controllers/arm_trajectory_controller
      - controllers/mast_controller
      - controllers/card_controller
      - controllers/hand_controller
      - controllers/stone_platform_controller
    calibration_controllers:
      - controllers/mast_calibration_controller
      - controllers/joint5_calibration_controller
      - controllers/joint4_calibration_controller
      - controllers/joint3_calibration_controller
      - controllers/joint2_calibration_controller
      - controllers/joint1_calibration_controller
      - controllers/hand_calibration_controller
      - controllers/card_calibration_controller
      - controllers/stone_platform_calibration_controller
      - controllers/yaw_calibration_controller
      - controllers/pitch_calibration_controller

  power_on_calibration:
    - start_controller: controllers/yaw_calibration_controller
      stop_controller: controllers/gimbal_controller
      service_name: /controllers/yaw_calibration_controller/is_calibrated
    - start_controller: controllers/pitch_calibration_controller
      stop_controller: controllers/gimbal_controller
      service_name: /controllers/pitch_calibration_controller/is_calibrated
    - start_controller: controllers/card_calibration_controller
      stop_controller: controllers/card_controller
      service_name: /controllers/card_calibration_controller/is_calibrated
    - start_controller: controllers/stone_platform_calibration_controller
      stop_controller: controllers/stone_platform_controller
      service_name: /controllers/stone_platform_calibration_controller/is_calibrated

  mast_calibration:
    - start_controller: controllers/mast_calibration_controller
      stop_controller: controllers/mast_controller
      service_name: /controllers/mast_calibration_controller/is_calibrated
  arm_calibration:
    - start_controller: controllers/joint1_calibration_controller
      stop_controller: controllers/arm_trajectory_controller
      service_name: /controllers/joint1_calibration_controller/is_calibrated
    - start_controller: controllers/joint2_calibration_controller
      stop_controller: controllers/arm_trajectory_controller
      service_name: /controllers/joint2_calibration_controller/is_calibrated
    - start_controller: controllers/joint3_calibration_controller
      stop_controller: controllers/arm_trajectory_controller
      service_name: /controllers/joint3_calibration_controller/is_calibrated
    - start_controller: controllers/joint4_calibration_controller
      stop_controller: controllers/arm_trajectory_controller
      service_name: /controllers/joint4_calibration_controller/is_calibrated
    - start_controller: controllers/joint5_calibration_controller
      stop_controller: controllers/arm_trajectory_controller
      service_name: /controllers/joint5_calibration_controller/is_calibrated
    - start_controller: controllers/hand_calibration_controller
      stop_controller: controllers/hand_controller
      service_name: /controllers/hand_calibration_controller/is_calibrated
  ui:
    trigger_change:
      - name: "step"
        config: { start_position: [ 400, 750 ], size: 15, width: 2, title: "step:  ", color: "white" }
      - name: "queue"
        config: { start_position: [ 400, 700 ], size: 15, width: 2, title: "queue: ", color: "yellow" }
      - name: "jog"
        config: { start_position: [ 1300, 750 ], size: 15, width: 2, title: "jog:  ", color: "white" }
      - name: "stone"
        config: { start_position: [ 1300, 700 ], size: 15, width: 2, title: "stone:", color: "yellow" }
      - name: "card"
        config: { start_position: [ 1300, 650 ], size: 15, width: 2, title: "card: ", color: "green" }
      - name: "sentry"
        config: { start_position: [ 1550, 750 ], size: 15, width: 2, title: "sentry:", color: "white" }
    fixed:
      - name: "stone_left"
        config: { type: "line", width: 2, color: "cyan",
                  start_position: [ 780, 401 ], end_position: [ 858, 571 ] }
      - name: "stone_right"
        config: { type: "line", width: 2, color: "cyan",
                  start_position: [ 1140, 386 ], end_position: [ 1124, 509 ] }
    time_change:
      - name: "effort"
        config: { start_position: [ 1500, 550 ], size: 15, width: 2, delay: 0.8 }
      - name: "temperature"
        config: { start_position: [ 1500, 500 ], size: 15, width: 2, delay: 0.8, title: "temp:   " }
      - name: "progress"
        config: { start_position: [ 400, 650 ], size: 15, width: 2, delay: 0.3, color: "green", title: "progress:" }
    flash:
      - name: "calibration"
        config: { start_position: [ 850, 700 ], size: 15, width: 2,
                  color: "yellow", content: "please calibrate!!", delay: 0.8 }
      - name: "card_warning"
        config: { start_position: [ 850, 750 ], size: 15, width: 2,
                  color: "green", content: "card stuck!!", delay: 0.8 }