rm_manual:
  robot_type: "standard"
  control_param:
    accel_x: 8.0
    accel_y: 8.0
    accel_angular: 10
    brake_multiple: 1.5
    expect_shoot_hz: 12
    safe_shoot_hz: 3
    safe_shoot_speed: 15.0
    gimbal_error_limit: 0.01
    rc_param:
      coefficient_x: 5.0
      coefficient_y: 5.0
      coefficient_angular: 5.0
      coefficient_yaw: 12.56
      coefficient_pitch: 12.56
    pc_param:
      coefficient_x: 5.0
      coefficient_y: 5.0
      coefficient_angular: 3.0
      coefficient_yaw: 750.0
      coefficient_pitch: 750.0
      normal_critical_speed: 0.5
      burst_critical_speed: 1.0
      normal_angular: 4.0
      burst_angular: 6.0
      spin_sin_amplitude: 3.0
      spin_sin_frequency: 6.28
  power_limit:
    safety_power: 50
    have_power_manager: true


